---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity <- read.csv('activity.csv', colClasses=c("integer", "Date", "integer"))

## What is mean total number of steps taken per day?
sums <- c(aggregate(ts(activity$steps, freq = 288), 1, sum, na.rm = TRUE))
dates <- c(unique(activity$date))
days <- data.frame(dates, sums)
hist(days$sums, freq=TRUE, xlab="Number of Steps", main="Total Number of Steps per Day")
mean(days$sums)
median(days$sums)

## What is the average daily activity pattern?
intervalAverages <- aggregate.data.frame(activity$steps, list(activity$interval), mean, na.rm=TRUE)
plot(intervalAverages[,1], intervalAverages[,2], type = "l", main = "Interval Average Across All Days", xlab = "Interval", ylab = "Number of Steps")

intervalAverages[which.max(intervalAverages[,2]),]

## Inputing missing values
nas<-data.frame(which(is.na(activity)), activity[which(is.na(activity)),])
nrow(nas)

newActivity <- activity
for (i in 1:length(newActivity[,1])) {
    if (is.na(newActivity[i,1])) {
        newActivity[i,1] <- intervalAverages[intervalAverages[,1] == newActivity[i,3], 2]
    }
}

sums <- c(aggregate(ts(newActivity$steps, freq = 288), 1, sum, na.rm = TRUE))
dates <- c(unique(newActivity$date))

days <- data.frame(dates, sums)
hist(days$sums, freq=TRUE, xlab="Number of Steps", main="Total Number of Steps per Day")
mean(days$sums)
median(days$sums)

## Are there differences in activity patterns between weekdays and weekends?
finalActivity <- activity
dayType <- lapply(weekdays.Date(finalActivity$date), function(x) { if(x == "Saturday" || x == "Sunday") { return("weekend") } else { return("weekday") } })
dayType.f <- factor(dayType, levels = c("weekday", "weekend"))
finalActivity$dayType <- dayType.f

dayTypeIntervalAverages <- aggregate.data.frame(finalActivity$steps, list(finalActivity$interval, finalActivity$dayType), mean, na.rm=TRUE)

plot(dayTypeIntervalAverages[,1], dayTypeIntervalAverages[,3], type = "l", main="Average Steps per Interval by Day Type", xlab = "Interval", ylab = "Steps")
